name: QA

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"

jobs:
  security-scan:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - run: docker run -v ${PWD}:/src aquasec/tfsec:v1.8 /src

  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0
      - uses: terraform-linters/setup-tflint@v4
        name: Setting up TFLint
      - name: Initializing TFLint
        run: tflint --init
      - name: Linting
        run: tflint -f compact

  qa:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Format
        run: terraform fmt -check -recursive
