name: QA

on:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: "true"

jobs:
  security-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: tfsec
        uses: triat/terraform-security-scan@v3.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  qa:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform Format
        run: terraform fmt -check -recursive
