name: Tests

on:
  push:
    branches: ["main"]
    tags-ignore: ["**"]
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  CLOUDSDK_CORE_PROJECT: "koenighotze-seed"
  # Note: this project has to exist for 'plan' to execute
  TF_VAR_project_id: "koenighotze-seed"

permissions:
  id-token: write

jobs:
  deployer-service-account:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: deployer-service-account/test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticating
        uses: google-github-actions/auth@v0.6.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.CICD_SA_EMAIL_ADDRESS }}
          token_format: 'access_token'
      - name: Setting up GCP environment
        uses: google-github-actions/setup-gcloud@v0.5.1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate
      - name: Plan
        run: terraform plan -no-color

  infrastructure-project:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: infrastructure-project/test
    env:
      TF_VAR_seed_sa_email_address: ${{ secrets.CICD_SA_EMAIL_ADDRESS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticating
        uses: google-github-actions/auth@v0.6.0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.CICD_SA_EMAIL_ADDRESS }}
          token_format: 'access_token'
      - name: Setting up GCP environment
        uses: google-github-actions/setup-gcloud@v0.5.1
        with:
          export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate
      - name: Plan
        run: terraform plan -no-color
